### PR TITLE
Add zeros iterator

### LINKED ISSUE #7: Add iter_ones() and iter_zeros() iterator.
Having an iterator over the bits that are set to ```1``` (or ```0```) would be a nice addition. For example, it would speed up [this loop](https://github.com/mneumann/munkres-rs/blob/master/src/coverage.rs#L42-L45) of my Kuhn-Munkres implementation. I could implement it myself by using the ```as_slice()``` method, but this would make assumptions about the order in which bits are stored in the ```u32```. This can be efficiently implemented using ```bsf``` (bit-scan-forward x86) or equivalent operations.

### PR DESCRIPTION
**Pull request by fuine**
This closes #7 and #9. I have written the code such that it 'just works' and is not pathological in terms of speed. As mentioned in #9 once i will have more time i will gladly make both iterators optimal. @bluss tell me what do you think about the proposed implementation.

### CODE REVIEW

**Comment by bluss** [comment]
Looks good. If you need this for your project, please use it locally.

**Comment by fuine** [comment]
While using the `zeros` iterator i have hit an edge-case -- if the bitset consisted of only one block, then it wouldn't get masked and so it would yield indices higher than length of the bitset. I have fixed that behavior and added unit tests to test this case for both `zeros` and `ones` iterators. Hopefully this was the last bug in this PR :)

**Comment by fuine** [comment]
I cherry-picked inline `count_ones` inline commit to this branch, as i'm using it for the project. If this is a problem then i will revert it and manage otherwise, although for simplicity reasons i would like to leave it here, especially if you are not planning on merging this PR soon. Btw i think that it is ready to be merged as-is.

**Comment by james7132** [comment]
Closing in favor of #89. Will try to adopt the benchmarks you have here for that implementation.

**Pull request closed without merging**
